### ISSUE TITLE
включение дверей

### ISSUE THREAD

**Issue by sntxerror** [b4ck5p4c3/spacebot#5]
перед включением надо допилить двойной контроль для открытия дверей и решить как быть с тестовыми новичками в чате

**Comment by sntxerror** [comment]
обсудили с @glitchcore, решили что нужно для бота иметь такой же список как для ключей. по хорошему здесь нам нужно поднимать IDP с разграничением доступа к тем или иным сервисам (инструментам).

**Comment by imcatwhocode** [comment]
@sntxerror мне не очень нравится эта идея тем, что она усложняет логику бота и онбординг новых котиков (IdP нужно будет знать ещё и Telegram ID каждой учётки). Я бы предложил оставить эту идею на потом, когда все более приоритетные IdP-задачи будут решены, а пока воспользоваться весьма нативненьким функционалом Администраторов. 

Идея в том, что мы можем выдавать статус администратора в жёлтом чате только доверенным участникам, а Telegram API нам, вдогонку с каждым сообщением боту, заботливо кладёт флаг отражающий наличие прав администратора у аккаунта, с которого было отправлено это сообщение.

/cc @glitchcore

**Comment by sntxerror** [comment]
@imcatwhocode мне нра!
